package com.willag.assistbot.ui.theme
import androidx.compose.ui.graphics.Color

val primaryLight = Color(0xFF005AB5)
val onPrimaryLight = Color(0xFFFFFFFF)
val primaryContainerLight = Color(0xFF0072E3)
val onPrimaryContainerLight = Color(0xFFFEFCFF)
val secondaryLight = Color(0xFF435F8E)
val onSecondaryLight = Color(0xFFFFFFFF)
val secondaryContainerLight = Color(0xFFABC7FD)
val onSecondaryContainerLight = Color(0xFF365282)
val tertiaryLight = Color(0xFF005DA8)
val onTertiaryLight = Color(0xFFFFFFFF)
val tertiaryContainerLight = Color(0xFF0076D2)
val onTertiaryContainerLight = Color(0xFFFDFCFF)
val errorLight = Color(0xFFBA1A1A)
val onErrorLight = Color(0xFFFFFFFF)
val errorContainerLight = Color(0xFFFFDAD6)
val onErrorContainerLight = Color(0xFF93000A)
val backgroundLight = Color(0xFFF9F9FF)
val onBackgroundLight = Color(0xFF181C23)
val surfaceLight = Color(0xFFFCF8F8)
val onSurfaceLight = Color(0xFF1C1B1B)
val surfaceVariantLight = Color(0xFFE3E2E7)
val onSurfaceVariantLight = Color(0xFF46464B)
val outlineLight = Color(0xFF76777C)
val outlineVariantLight = Color(0xFFC7C6CB)
val scrimLight = Color(0xFF000000)
val inverseSurfaceLight = Color(0xFF313030)
val inverseOnSurfaceLight = Color(0xFFF4F0EF)
val inversePrimaryLight = Color(0xFFAAC7FF)
val surfaceDimLight = Color(0xFFDDD9D9)
val surfaceBrightLight = Color(0xFFFCF8F8)
val surfaceContainerLowestLight = Color(0xFFFFFFFF)
val surfaceContainerLowLight = Color(0xFFF7F3F2)
val surfaceContainerLight = Color(0xFFF1EDEC)
val surfaceContainerHighLight = Color(0xFFEBE7E7)
val surfaceContainerHighestLight = Color(0xFFE5E2E1)

val primaryDark = Color(0xFFAAC7FF)
val onPrimaryDark = Color(0xFF002F65)
val primaryContainerDark = Color(0xFF418FFF)
val onPrimaryContainerDark = Color(0xFF00214A)
val secondaryDark = Color(0xFFABC7FD)
val onSecondaryDark = Color(0xFF0F305D)
val secondaryContainerDark = Color(0xFF2C4978)
val onSecondaryContainerDark = Color(0xFF9DB9EE)
val tertiaryDark = Color(0xFFA4C9FF)
val onTertiaryDark = Color(0xFF00315D)
val tertiaryContainerDark = Color(0xFF1A92FF)
val onTertiaryContainerDark = Color(0xFF002A51)
val errorDark = Color(0xFFFFB4AB)
val onErrorDark = Color(0xFF690005)
val errorContainerDark = Color(0xFF93000A)
val onErrorContainerDark = Color(0xFFFFDAD6)
val backgroundDark = Color(0xFF10131A)
val onBackgroundDark = Color(0xFFE0E2EC)
val surfaceDark = Color(0xFF141313)
val onSurfaceDark = Color(0xFFE5E2E1)
val surfaceVariantDark = Color(0xFF46464B)
val onSurfaceVariantDark = Color(0xFFC7C6CB)
val outlineDark = Color(0xFF909095)
val outlineVariantDark = Color(0xFF46464B)
val scrimDark = Color(0xFF000000)
val inverseSurfaceDark = Color(0xFFE5E2E1)
val inverseOnSurfaceDark = Color(0xFF313030)
val inversePrimaryDark = Color(0xFF005CBA)
val surfaceDimDark = Color(0xFF141313)
val surfaceBrightDark = Color(0xFF3A3939)
val surfaceContainerLowestDark = Color(0xFF0E0E0E)
val surfaceContainerLowDark = Color(0xFF1C1B1B)
val surfaceContainerDark = Color(0xFF201F1F)
val surfaceContainerHighDark = Color(0xFF2A2A2A)
val surfaceContainerHighestDark = Color(0xFF353434)





